dist: trusty
sudo: required
language: cpp

env:
  - CXX_STANDARD=98
  - CXX_STANDARD=11
  - CXX_STANDARD=14
  - CXX_STANDARD=17

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install cmake libboost-all-dev libxerces-c-dev libxalan-c-dev
  - cmake --version
  - travis_retry wget https://github.com/mat007/turtle/archive/master.zip
  - unzip master.zip
  - cp -r turtle-master/include/turtle src/libraries

script:
  - mkdir -p build/cmake
  - cd build/cmake
  - cmake ../.. -DCMAKE_CXX_STANDARD=${CXX_STANDARD}
  - cmake --build .
  - ctest --verbose
